package com.example.casestudymodulejavaspringboot.casestudymodulejavaspringboot.repository;

import com.example.casestudymodulejavaspringboot.casestudymodulejavaspringboot.entity.FuramaKhachHang;
import org.springframework.data.repository.PagingAndSortingRepository;

public interface RepositoryKhachHang extends PagingAndSortingRepository<FuramaKhachHang,Long> {
}
